#!/bin/bash

isError=0
git diff --cached --check
# Check a specific file and exit with 1 if the newline is missing
isError=$?

for f in $(git ls-files); do
    if [[ "$(tail -c1 $f)" ]]; then
        isError=1
        echo >> $f
        echo "Added newline to $f"
    fi
done

if [ "$isError" -eq 1 ]; then
    exit 1
else
    exit 0
fi
